Detailed error message on hook registration conflict
pytest-dev/pluggy pull request #379
Opened 2023-03-24 05:34 UTC by vitek

Hi! I've spent some time trying to nail down hook registration error:

```python
INTERNALERROR>     pluginmanager.add_hookspecs(Hookspec)
INTERNALERROR>   File "contrib/python/pluggy/py3/pluggy/_manager.py", line 175, in add_hookspecs
INTERNALERROR>     hc.set_specification(module_or_class, spec_opts)
INTERNALERROR>   File "contrib/python/pluggy/py3/pluggy/_hooks.py", line 200, in set_specification
INTERNALERROR>     assert not self.has_spec()
INTERNALERROR> AssertionError
```

This PR raises `RuntimeError` with detailed message which should ease developer's life a bit:

```python
E           RuntimeError: Hook 'conflict' is already registered within namespace <class 'test_hookcaller.test_hook_conflict.<locals>.Api1'>

src/pluggy/_hooks.py:341: RuntimeError
```

2023-03-24 05:49 UTC, RonnyPfannschmidt requested changes
Thank you for getting this started, the pr is well prepared. 

Please have a look at my comments.

2023-03-24 05:49 UTC, RonnyPfannschmidt commented on src/pluggy/_hooks.py
> +            raise RuntimeError(
This ough to be a ValueError or a subclass of it

2023-03-24 05:49 UTC, RonnyPfannschmidt commented on testing/test_hookcaller.py
> +    with pytest.raises(RuntimeError):
Please add a check for the message, just to be safe

2023-03-24 08:03 UTC, RonnyPfannschmidt approved these changes
Well done, would you like to compact history or squash?

2023-03-24 08:15 UTC, vitek commented
I usually do squash on merge. Should I do it myself?

2023-03-24 08:46 UTC, RonnyPfannschmidt commented
We currently don't have squash merge enabled on the repo, but of you consent to squash I'll happily do it later today after enabling

2023-03-24 11:55 UTC, nicoddemus approved these changes
LGTM, would you like to add a CHANGELOG entry as well?

2023-03-24 12:54 UTC, vitek commented
> LGTM, would you like to add a CHANGELOG entry as well?

No thank you, it's minor fix. Still can add line if it's required.

2023-06-21 06:00 UTC, bluetech approved these changes
Thanks!

2023-06-21 06:00 UTC, merged